import type {
  Badge,
  BlogPost,
  ContentType,
  Lesson,
  Locale,
  MediaAsset,
  Product,
  Author,
} from "@/types";

export const LOCALES: Locale[] = [
  { code: "en", name: "English", flag: "🇺🇸", isDefault: true },
  { code: "de", name: "German", flag: "🇩🇪", isDefault: false },
  { code: "fr", name: "French", flag: "🇫🇷", isDefault: false },
  { code: "es", name: "Spanish", flag: "🇪🇸", isDefault: false },
];

export const BADGES: Badge[] = [
  {
    id: "badge-1",
    slug: "content-creator",
    name: "Content Creator",
    description: "Created your first blog post",
    icon: "✍️",
    color: "#6366f1",
    earned: false,
  },
  {
    id: "badge-2",
    slug: "live-content",
    name: "Live Content",
    description: "Experienced real-time content updates",
    icon: "⚡",
    color: "#8b5cf6",
    earned: false,
  },
  {
    id: "badge-3",
    slug: "media-manager",
    name: "Media Manager",
    description: "Uploaded and managed media assets",
    icon: "🖼️",
    color: "#ec4899",
    earned: false,
  },
  {
    id: "badge-4",
    slug: "schema-architect",
    name: "Schema Architect",
    description: "Built custom content models",
    icon: "🏗️",
    color: "#14b8a6",
    earned: false,
  },
  {
    id: "badge-5",
    slug: "global-publisher",
    name: "Global Publisher",
    description: "Published content in multiple languages",
    icon: "🌍",
    color: "#f59e0b",
    earned: false,
  },
  {
    id: "badge-6",
    slug: "publishing-expert",
    name: "Publishing Expert",
    description: "Mastered draft and publish workflow",
    icon: "📤",
    color: "#10b981",
    earned: false,
  },
  {
    id: "badge-7",
    slug: "access-control",
    name: "Access Control",
    description: "Understood CMS permissions",
    icon: "🔐",
    color: "#ef4444",
    earned: false,
  },
];

export const LESSONS: Lesson[] = [
  {
    id: "lesson-1",
    slug: "content-creation",
    title: "Content Creation",
    description: "Create your first blog post and see it appear on the website",
    order: 1,
    xpReward: 100,
    badge: BADGES[0],
    completed: false,
    progress: 0,
    tasks: [
      {
        id: "task-1-1",
        description: "Open the Blog Posts content type",
        completed: false,
        hint: "Click on Blog Posts in the CMS panel",
      },
      {
        id: "task-1-2",
        description: "Create a new blog post with a title",
        completed: false,
        hint: "Fill in the title field and save",
      },
      {
        id: "task-1-3",
        description: "Publish the post and see it on the homepage",
        completed: false,
        hint: "Toggle status to Published",
      },
    ],
  },
  {
    id: "lesson-2",
    slug: "real-time-updates",
    title: "Real-Time Updates",
    description: "Change content and watch it update instantly",
    order: 2,
    xpReward: 150,
    badge: BADGES[1],
    completed: false,
    progress: 0,
    tasks: [
      {
        id: "task-2-1",
        description: "Edit an existing blog post title",
        completed: false,
      },
      {
        id: "task-2-2",
        description: "Watch the API response update in real-time",
        completed: false,
      },
      {
        id: "task-2-3",
        description: "See the frontend preview change instantly",
        completed: false,
      },
    ],
  },
  {
    id: "lesson-3",
    slug: "media-management",
    title: "Media Management",
    description: "Upload and manage media assets",
    order: 3,
    xpReward: 150,
    badge: BADGES[2],
    completed: false,
    progress: 0,
    tasks: [
      {
        id: "task-3-1",
        description: "Open the Media Manager",
        completed: false,
      },
      {
        id: "task-3-2",
        description: "Upload an image asset",
        completed: false,
      },
      {
        id: "task-3-3",
        description: "Assign the image to a blog post hero section",
        completed: false,
      },
    ],
  },
  {
    id: "lesson-4",
    slug: "content-modeling",
    title: "Content Modeling",
    description: "Add custom fields to your content types",
    order: 4,
    xpReward: 200,
    badge: BADGES[3],
    completed: false,
    progress: 0,
    tasks: [
      {
        id: "task-4-1",
        description: "Open Content Modeling",
        completed: false,
      },
      {
        id: "task-4-2",
        description: 'Add a "Reading Time" number field',
        completed: false,
      },
      {
        id: "task-4-3",
        description: "See the new field appear on the frontend",
        completed: false,
      },
    ],
  },
  {
    id: "lesson-5",
    slug: "localization",
    title: "Localization",
    description: "Publish content in multiple languages",
    order: 5,
    xpReward: 200,
    badge: BADGES[4],
    completed: false,
    progress: 0,
    tasks: [
      {
        id: "task-5-1",
        description: "Enable German language",
        completed: false,
      },
      {
        id: "task-5-2",
        description: "Create a German translation of a post",
        completed: false,
      },
      {
        id: "task-5-3",
        description: "Switch frontend language and see the change",
        completed: false,
      },
    ],
  },
  {
    id: "lesson-6",
    slug: "draft-publish",
    title: "Draft & Publish",
    description: "Understand the draft and publish workflow",
    order: 6,
    xpReward: 150,
    badge: BADGES[5],
    completed: false,
    progress: 0,
    tasks: [
      {
        id: "task-6-1",
        description: "Save content as draft",
        completed: false,
      },
      {
        id: "task-6-2",
        description: "Verify frontend does NOT update",
        completed: false,
      },
      {
        id: "task-6-3",
        description: "Publish and see frontend update",
        completed: false,
      },
    ],
  },
  {
    id: "lesson-7",
    slug: "permissions",
    title: "Permissions & Roles",
    description: "Learn about CMS access control",
    order: 7,
    xpReward: 250,
    badge: BADGES[6],
    completed: false,
    progress: 0,
    tasks: [
      {
        id: "task-7-1",
        description: "Switch to Viewer role",
        completed: false,
      },
      {
        id: "task-7-2",
        description: "Observe restricted features",
        completed: false,
      },
      {
        id: "task-7-3",
        description: "Switch to Admin and restore full access",
        completed: false,
      },
    ],
  },
];

export const CONTENT_TYPES: ContentType[] = [
  {
    id: "ct-1",
    slug: "blog-posts",
    name: "Blog Posts",
    icon: "FileText",
    fields: [
      { id: "f-1", name: "Title", slug: "title", fieldType: "text", required: true, order: 0 },
      { id: "f-2", name: "Slug", slug: "slug", fieldType: "slug", required: true, order: 1 },
      { id: "f-3", name: "Author", slug: "author", fieldType: "reference", required: true, order: 2 },
      { id: "f-4", name: "Image", slug: "image", fieldType: "image", required: false, order: 3 },
      { id: "f-5", name: "Content", slug: "content", fieldType: "richtext", required: true, order: 4 },
      { id: "f-6", name: "Category", slug: "category", fieldType: "select", required: false, order: 5 },
      { id: "f-7", name: "Status", slug: "status", fieldType: "select", required: true, order: 6 },
    ],
  },
  {
    id: "ct-2",
    slug: "products",
    name: "Products",
    icon: "ShoppingBag",
    fields: [
      { id: "f-8", name: "Name", slug: "name", fieldType: "text", required: true, order: 0 },
      { id: "f-9", name: "Price", slug: "price", fieldType: "number", required: true, order: 1 },
      { id: "f-10", name: "Image", slug: "image", fieldType: "image", required: false, order: 2 },
      { id: "f-11", name: "Description", slug: "description", fieldType: "richtext", required: false, order: 3 },
    ],
  },
  {
    id: "ct-3",
    slug: "authors",
    name: "Authors",
    icon: "User",
    fields: [
      { id: "f-12", name: "Name", slug: "name", fieldType: "text", required: true, order: 0 },
      { id: "f-13", name: "Bio", slug: "bio", fieldType: "richtext", required: false, order: 1 },
      { id: "f-14", name: "Avatar", slug: "avatar", fieldType: "image", required: false, order: 2 },
    ],
  },
  {
    id: "ct-4",
    slug: "pages",
    name: "Pages",
    icon: "Layout",
    fields: [
      { id: "f-15", name: "Title", slug: "title", fieldType: "text", required: true, order: 0 },
      { id: "f-16", name: "Content", slug: "content", fieldType: "richtext", required: true, order: 1 },
    ],
  },
  {
    id: "ct-5",
    slug: "categories",
    name: "Categories",
    icon: "Tag",
    fields: [
      { id: "f-17", name: "Name", slug: "name", fieldType: "text", required: true, order: 0 },
      { id: "f-18", name: "Slug", slug: "slug", fieldType: "slug", required: true, order: 1 },
    ],
  },
  {
    id: "ct-6",
    slug: "media",
    name: "Media",
    icon: "Image",
    fields: [],
  },
  {
    id: "ct-7",
    slug: "users",
    name: "Users",
    icon: "Users",
    fields: [
      { id: "f-19", name: "Name", slug: "name", fieldType: "text", required: true, order: 0 },
      { id: "f-20", name: "Email", slug: "email", fieldType: "text", required: true, order: 1 },
      { id: "f-21", name: "Role", slug: "role", fieldType: "select", required: true, order: 2 },
    ],
  },
];

export const INITIAL_POSTS: BlogPost[] = [
  {
    id: "post-1",
    title: "Hello World",
    slug: "hello-world",
    author: "Sarah Chen",
    image: "https://images.unsplash.com/photo-1499750310107-5fef28fd666f?w=800&h=400&fit=crop",
    content: "<p>Welcome to LearnCMS! This is your first blog post. Edit this content in the CMS panel and watch it update in real-time on the frontend preview.</p><p>Headless CMS architecture separates content management from presentation, giving developers freedom to build with any framework.</p>",
    category: "Getting Started",
    status: "published",
    locale: "en",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "post-2",
    title: "Understanding Headless CMS",
    slug: "understanding-headless-cms",
    author: "Alex Rivera",
    image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&h=400&fit=crop",
    content: "<p>A headless CMS is a back-end only content management system that serves content via APIs. Unlike traditional CMS platforms, it has no built-in frontend.</p>",
    category: "Architecture",
    status: "published",
    locale: "en",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    name: "CMS Starter Kit",
    slug: "cms-starter-kit",
    price: 49,
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=400&fit=crop",
    description: "Everything you need to start building with headless CMS",
    status: "published",
  },
  {
    id: "prod-2",
    name: "API Integration Pack",
    slug: "api-integration-pack",
    price: 79,
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=400&fit=crop",
    description: "Pre-built integrations for popular CMS platforms",
    status: "published",
  },
  {
    id: "prod-3",
    name: "Content Modeling Guide",
    slug: "content-modeling-guide",
    price: 29,
    image: "https://images.unsplash.com/photo-1504639725590-34d0984388bd?w=400&h=400&fit=crop",
    description: "Learn to design flexible content schemas",
    status: "published",
  },
];

export const INITIAL_AUTHORS: Author[] = [
  {
    id: "author-1",
    name: "Sarah Chen",
    bio: "Senior content strategist with 10 years of experience in digital publishing.",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
  },
  {
    id: "author-2",
    name: "Alex Rivera",
    bio: "Full-stack developer specializing in headless architecture and JAMstack.",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop",
  },
];

export const INITIAL_MEDIA: MediaAsset[] = [
  {
    id: "media-1",
    filename: "hero-banner.jpg",
    url: "https://images.unsplash.com/photo-1499750310107-5fef28fd666f?w=800&h=400&fit=crop",
    mimeType: "image/jpeg",
    size: 245000,
    alt: "Hero banner",
  },
  {
    id: "media-2",
    filename: "coding-setup.jpg",
    url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&h=400&fit=crop",
    mimeType: "image/jpeg",
    size: 312000,
    alt: "Coding setup",
  },
];

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    heroTitle: "Build with Headless CMS",
    heroSubtitle: "Learn how content flows from CMS to your website",
    readMore: "Read More",
    viewProducts: "View Products",
    aboutTitle: "About LearnCMS",
    aboutContent: "We're on a mission to make headless CMS concepts accessible to everyone through interactive learning.",
    blogTitle: "Latest Articles",
    productsTitle: "Our Products",
    navHome: "Home",
    navBlog: "Blog",
    navProducts: "Products",
    navAbout: "About",
  },
  de: {
    heroTitle: "Mit Headless CMS bauen",
    heroSubtitle: "Lernen Sie, wie Inhalte vom CMS zur Website fließen",
    readMore: "Weiterlesen",
    viewProducts: "Produkte ansehen",
    aboutTitle: "Über LearnCMS",
    aboutContent: "Unsere Mission ist es, Headless-CMS-Konzepte durch interaktives Lernen für alle zugänglich zu machen.",
    blogTitle: "Neueste Artikel",
    productsTitle: "Unsere Produkte",
    navHome: "Startseite",
    navBlog: "Blog",
    navProducts: "Produkte",
    navAbout: "Über uns",
  },
  fr: {
    heroTitle: "Construire avec un CMS Headless",
    heroSubtitle: "Découvrez comment le contenu circule du CMS vers votre site",
    readMore: "Lire la suite",
    viewProducts: "Voir les produits",
    aboutTitle: "À propos de LearnCMS",
    aboutContent: "Notre mission est de rendre les concepts de CMS headless accessibles à tous grâce à l'apprentissage interactif.",
    blogTitle: "Derniers articles",
    productsTitle: "Nos produits",
    navHome: "Accueil",
    navBlog: "Blog",
    navProducts: "Produits",
    navAbout: "À propos",
  },
  es: {
    heroTitle: "Construye con CMS Headless",
    heroSubtitle: "Aprende cómo el contenido fluye del CMS a tu sitio web",
    readMore: "Leer más",
    viewProducts: "Ver productos",
    aboutTitle: "Acerca de LearnCMS",
    aboutContent: "Nuestra misión es hacer accesibles los conceptos de CMS headless para todos a través del aprendizaje interactivo.",
    blogTitle: "Últimos artículos",
    productsTitle: "Nuestros productos",
    navHome: "Inicio",
    navBlog: "Blog",
    navProducts: "Productos",
    navAbout: "Acerca de",
  },
};
